todo_app/urls.py
from django.urls import path

from todo_app.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskStatusUpdateView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="home-page"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/update_status/", TaskStatusUpdateView.as_view(), name="task-update-status"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_app.urls", namespace="todo"))
]

todo_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class TaskSolver(AbstractUser):
    pass


class Tag(models.Model):
    name = models.CharField(max_length=65, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(blank=True, null=True)
    is_done = models.BooleanField(blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return f"{self.content}, created: {self.datetime}"

todo_app/forms.py
from django import forms
from django.forms import SelectDateWidget

from todo_app.models import Task


class TaskForm(forms.ModelForm):
    deadline = forms.DateField(
        required=False,
        widget=SelectDateWidget(
            empty_label=("Choose Year", "Choose Month", "Choose Day"),
        ),
    )

    class Meta:
        model = Task
        fields = "__all__"

todo_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic

from todo_app.forms import TaskForm
from todo_app.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task

    def get_queryset(self):
        return Task.objects.all().order_by("-datetime")


class TaskCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("todo:home-page")
    form_class = TaskForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    success_url = reverse_lazy("todo:home-page")
    form_class = TaskForm


class TaskStatusUpdateView(generic.View):
    def post(self, request, pk):
        task = get_object_or_404(Task, id=pk)
        task.is_done = not task.is_done
        task.save()
        return HttpResponseRedirect(reverse("todo:home-page"))


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:home-page")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>ToDo App</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:home-page' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo_app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag {{ tag.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Submit">
  </form>
{% endblock %}

templates/todo_app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create new tag</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

templates/todo_app/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags</h1>
  <a href="{% url 'todo:tag-create' %}">
    <button type="button" class="btn btn-primary">Add tag</button>
  </a>
  <br><br>

  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
    <tr>
      <td>{{ tag.name }}</td>
      <td>
        <a href="{% url 'todo:tag-update' pk=tag.id %}">
          <button type="button" class="btn btn-secondary">Update</button>
        </a>
      </td>
      <td>
        <a href="{% url 'todo:tag-delete' pk=tag.id %}">
          <button type="button" class="btn btn-secondary">Delete</button>
        </a>
      </td>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/todo_app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete task?</h1>
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger">
</form>
{% endblock %}

templates/todo_app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

templates/todo_app/task_list.html
{% extends "base.html" %}
{% load task_status %}

{% block content %}
  <h1>Task List</h1>
  <a href="{% url 'todo:task-create' %}">
    <button type="button" class="btn btn-primary">Add task</button>
  </a>
  <br><br>

  <table class="table">
    {% for task in task_list %}
    <tr>
      <td>
        <p class="task-content">
          {{ task.content }}:
          <span class="is_done">{{ task.is_done|display_task_status }}</span>
        </p>
        <p>
          Created at: {{ task.datetime }}
          <span class="deadline">Deadline: {{ task.deadline }}</span>
        </p>
        <br>
        <p class="tag">Tags:
          {% for tag in task.tags.all %}
            {{ tag }}
          {% endfor %}
          <a href="{% url 'todo:task-update' pk=task.id %}">Update</a>
          <a href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
        </p>
      </td>
      <td>
        <form action="{% url 'todo:task-update-status' pk=task.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="{{ task.is_done|transform_task_status }}">
        </form>
      </td>
    </tr>
    {% endfor %}
  </table>

{% endblock %}